spring:
  datasource:
    url: jdbc:mysql://xiaoxu.ltd:3407/study
    username: root
    password: Password01!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
server:
  port: 80